version: '3'
services:
  app_react:
    build: ./
    container_name: app_react
    volumes: 
      - build_react:/var/www/html
    depends_on:
      - nginx
  
  nginx: 
    build: ../nginx
    container_name: nginx
    ports: -80:80
    volumes: -build_react:/var/www/html
    depends_on:
      - app_react

volumes:
  build_react:
